//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildConfig) DeepCopyInto(out *BuildConfig) {
	*out = *in
	if in.RenderedMachineConfig != nil {
		in, out := &in.RenderedMachineConfig, &out.RenderedMachineConfig
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachineConfigPool != nil {
		in, out := &in.MachineConfigPool, &out.MachineConfigPool
		*out = new(v1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildConfig.
func (in *BuildConfig) DeepCopy() *BuildConfig {
	if in == nil {
		return nil
	}
	out := new(BuildConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCOObjectReference) DeepCopyInto(out *MCOObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCOObjectReference.
func (in *MCOObjectReference) DeepCopy() *MCOObjectReference {
	if in == nil {
		return nil
	}
	out := new(MCOObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNode) DeepCopyInto(out *MachineConfigNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNode.
func (in *MachineConfigNode) DeepCopy() *MachineConfigNode {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeList) DeepCopyInto(out *MachineConfigNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineConfigNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeList.
func (in *MachineConfigNodeList) DeepCopy() *MachineConfigNodeList {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeSpec) DeepCopyInto(out *MachineConfigNodeSpec) {
	*out = *in
	out.Node = in.Node
	out.Pool = in.Pool
	out.ConfigVersion = in.ConfigVersion
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeSpec.
func (in *MachineConfigNodeSpec) DeepCopy() *MachineConfigNodeSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeSpecMachineConfigVersion) DeepCopyInto(out *MachineConfigNodeSpecMachineConfigVersion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeSpecMachineConfigVersion.
func (in *MachineConfigNodeSpecMachineConfigVersion) DeepCopy() *MachineConfigNodeSpecMachineConfigVersion {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeSpecMachineConfigVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeStatus) DeepCopyInto(out *MachineConfigNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ConfigVersion = in.ConfigVersion
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeStatus.
func (in *MachineConfigNodeStatus) DeepCopy() *MachineConfigNodeStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeStatusMachineConfigVersion) DeepCopyInto(out *MachineConfigNodeStatusMachineConfigVersion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeStatusMachineConfigVersion.
func (in *MachineConfigNodeStatusMachineConfigVersion) DeepCopy() *MachineConfigNodeStatusMachineConfigVersion {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeStatusMachineConfigVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuild) DeepCopyInto(out *MachineOSBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuild.
func (in *MachineOSBuild) DeepCopy() *MachineOSBuild {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOSBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuildHistory) DeepCopyInto(out *MachineOSBuildHistory) {
	*out = *in
	in.Built.DeepCopyInto(&out.Built)
	out.ObjectReference = in.ObjectReference
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuildHistory.
func (in *MachineOSBuildHistory) DeepCopy() *MachineOSBuildHistory {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuildHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuildSpec) DeepCopyInto(out *MachineOSBuildSpec) {
	*out = *in
	in.BuildConfig.DeepCopyInto(&out.BuildConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuildSpec.
func (in *MachineOSBuildSpec) DeepCopy() *MachineOSBuildSpec {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuildStatus) DeepCopyInto(out *MachineOSBuildStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BuildHistory != nil {
		in, out := &in.BuildHistory, &out.BuildHistory
		*out = make([]MachineOSBuildHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BuildObjects != nil {
		in, out := &in.BuildObjects, &out.BuildObjects
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuildStatus.
func (in *MachineOSBuildStatus) DeepCopy() *MachineOSBuildStatus {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSImage) DeepCopyInto(out *MachineOSImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSImage.
func (in *MachineOSImage) DeepCopy() *MachineOSImage {
	if in == nil {
		return nil
	}
	out := new(MachineOSImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOSImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSImageInfo) DeepCopyInto(out *MachineOSImageInfo) {
	*out = *in
	out.RenderedMachineConfig = in.RenderedMachineConfig
	in.Built.DeepCopyInto(&out.Built)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSImageInfo.
func (in *MachineOSImageInfo) DeepCopy() *MachineOSImageInfo {
	if in == nil {
		return nil
	}
	out := new(MachineOSImageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSImageSpec) DeepCopyInto(out *MachineOSImageSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSImageSpec.
func (in *MachineOSImageSpec) DeepCopy() *MachineOSImageSpec {
	if in == nil {
		return nil
	}
	out := new(MachineOSImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSImageStatus) DeepCopyInto(out *MachineOSImageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.MachineOSImageInfo.DeepCopyInto(&out.MachineOSImageInfo)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSImageStatus.
func (in *MachineOSImageStatus) DeepCopy() *MachineOSImageStatus {
	if in == nil {
		return nil
	}
	out := new(MachineOSImageStatus)
	in.DeepCopyInto(out)
	return out
}
